/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AppRouteImport } from "./routes/_app";
import { Route as AppBinderRouteImport } from "./routes/_app.binder";
import { Route as AppDecksRouteImport } from "./routes/_app.decks";
import { Route as AppDecksBuilderDeckIdRouteImport } from "./routes/_app.decks.builder.$deckId";
import { Route as AppFriendsRouteImport } from "./routes/_app.friends";
import { Route as AppGuildsRouteImport } from "./routes/_app.guilds";
import { Route as AppProfilePlayerIdRouteImport } from "./routes/_app.profile.$playerId";
import { Route as GameRouteImport } from "./routes/_game";
import { Route as GamePlayMatchIdRouteImport } from "./routes/_game.play.$matchId";
import { Route as IndexRouteImport } from "./routes/index";

const GameRoute = GameRouteImport.update({
  id: "/_game",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppGuildsRoute = AppGuildsRouteImport.update({
  id: "/guilds",
  path: "/guilds",
  getParentRoute: () => AppRoute,
} as any);
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: "/friends",
  path: "/friends",
  getParentRoute: () => AppRoute,
} as any);
const AppDecksRoute = AppDecksRouteImport.update({
  id: "/decks",
  path: "/decks",
  getParentRoute: () => AppRoute,
} as any);
const AppBinderRoute = AppBinderRouteImport.update({
  id: "/binder",
  path: "/binder",
  getParentRoute: () => AppRoute,
} as any);
const GamePlayMatchIdRoute = GamePlayMatchIdRouteImport.update({
  id: "/play/$matchId",
  path: "/play/$matchId",
  getParentRoute: () => GameRoute,
} as any);
const AppProfilePlayerIdRoute = AppProfilePlayerIdRouteImport.update({
  id: "/profile/$playerId",
  path: "/profile/$playerId",
  getParentRoute: () => AppRoute,
} as any);
const AppDecksBuilderDeckIdRoute = AppDecksBuilderDeckIdRouteImport.update({
  id: "/builder/$deckId",
  path: "/builder/$deckId",
  getParentRoute: () => AppDecksRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/binder": typeof AppBinderRoute;
  "/decks": typeof AppDecksRouteWithChildren;
  "/friends": typeof AppFriendsRoute;
  "/guilds": typeof AppGuildsRoute;
  "/profile/$playerId": typeof AppProfilePlayerIdRoute;
  "/play/$matchId": typeof GamePlayMatchIdRoute;
  "/decks/builder/$deckId": typeof AppDecksBuilderDeckIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/binder": typeof AppBinderRoute;
  "/decks": typeof AppDecksRouteWithChildren;
  "/friends": typeof AppFriendsRoute;
  "/guilds": typeof AppGuildsRoute;
  "/profile/$playerId": typeof AppProfilePlayerIdRoute;
  "/play/$matchId": typeof GamePlayMatchIdRoute;
  "/decks/builder/$deckId": typeof AppDecksBuilderDeckIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_app": typeof AppRouteWithChildren;
  "/_game": typeof GameRouteWithChildren;
  "/_app/binder": typeof AppBinderRoute;
  "/_app/decks": typeof AppDecksRouteWithChildren;
  "/_app/friends": typeof AppFriendsRoute;
  "/_app/guilds": typeof AppGuildsRoute;
  "/_app/profile/$playerId": typeof AppProfilePlayerIdRoute;
  "/_game/play/$matchId": typeof GamePlayMatchIdRoute;
  "/_app/decks/builder/$deckId": typeof AppDecksBuilderDeckIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/binder"
    | "/decks"
    | "/friends"
    | "/guilds"
    | "/profile/$playerId"
    | "/play/$matchId"
    | "/decks/builder/$deckId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/binder"
    | "/decks"
    | "/friends"
    | "/guilds"
    | "/profile/$playerId"
    | "/play/$matchId"
    | "/decks/builder/$deckId";
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/_game"
    | "/_app/binder"
    | "/_app/decks"
    | "/_app/friends"
    | "/_app/guilds"
    | "/_app/profile/$playerId"
    | "/_game/play/$matchId"
    | "/_app/decks/builder/$deckId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  GameRoute: typeof GameRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_game": {
      id: "/_game";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof GameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/guilds": {
      id: "/_app/guilds";
      path: "/guilds";
      fullPath: "/guilds";
      preLoaderRoute: typeof AppGuildsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/friends": {
      id: "/_app/friends";
      path: "/friends";
      fullPath: "/friends";
      preLoaderRoute: typeof AppFriendsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/decks": {
      id: "/_app/decks";
      path: "/decks";
      fullPath: "/decks";
      preLoaderRoute: typeof AppDecksRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/binder": {
      id: "/_app/binder";
      path: "/binder";
      fullPath: "/binder";
      preLoaderRoute: typeof AppBinderRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_game/play/$matchId": {
      id: "/_game/play/$matchId";
      path: "/play/$matchId";
      fullPath: "/play/$matchId";
      preLoaderRoute: typeof GamePlayMatchIdRouteImport;
      parentRoute: typeof GameRoute;
    };
    "/_app/profile/$playerId": {
      id: "/_app/profile/$playerId";
      path: "/profile/$playerId";
      fullPath: "/profile/$playerId";
      preLoaderRoute: typeof AppProfilePlayerIdRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/decks/builder/$deckId": {
      id: "/_app/decks/builder/$deckId";
      path: "/builder/$deckId";
      fullPath: "/decks/builder/$deckId";
      preLoaderRoute: typeof AppDecksBuilderDeckIdRouteImport;
      parentRoute: typeof AppDecksRoute;
    };
  }
}

interface AppDecksRouteChildren {
  AppDecksBuilderDeckIdRoute: typeof AppDecksBuilderDeckIdRoute;
}

const AppDecksRouteChildren: AppDecksRouteChildren = {
  AppDecksBuilderDeckIdRoute: AppDecksBuilderDeckIdRoute,
};

const AppDecksRouteWithChildren = AppDecksRoute._addFileChildren(AppDecksRouteChildren);

interface AppRouteChildren {
  AppBinderRoute: typeof AppBinderRoute;
  AppDecksRoute: typeof AppDecksRouteWithChildren;
  AppFriendsRoute: typeof AppFriendsRoute;
  AppGuildsRoute: typeof AppGuildsRoute;
  AppProfilePlayerIdRoute: typeof AppProfilePlayerIdRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppBinderRoute: AppBinderRoute,
  AppDecksRoute: AppDecksRouteWithChildren,
  AppFriendsRoute: AppFriendsRoute,
  AppGuildsRoute: AppGuildsRoute,
  AppProfilePlayerIdRoute: AppProfilePlayerIdRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

interface GameRouteChildren {
  GamePlayMatchIdRoute: typeof GamePlayMatchIdRoute;
}

const GameRouteChildren: GameRouteChildren = {
  GamePlayMatchIdRoute: GamePlayMatchIdRoute,
};

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GameRoute: GameRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
