/**
 * Starter Deck Card Definitions
 *
 * Generated from launch_cards.csv
 * 45 cards per deck (30 monsters, 10 spells, 5 traps)
 */

import type { CardSeed } from "./types";

export const INFERNAL_DRAGONS_CARDS: readonly CardSeed[] = [
  // Monsters (30)
  {
    name: "Ember Wyrmling",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 3,
    attack: 1200,
    defense: 800,
  },
  {
    name: "Infernal Hatchling",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 2,
    attack: 800,
    defense: 600,
  },
  {
    name: "Scorched Serpent",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1400,
    defense: 1000,
  },
  {
    name: "Flame Whelp",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 1,
    attack: 600,
    defense: 400,
  },
  {
    name: "Blazing Drake",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1600,
    defense: 1200,
  },
  {
    name: "Cinder Wyrm",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 3,
    attack: 1100,
    defense: 700,
  },
  {
    name: "Magma Hatchling",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 2,
    attack: 900,
    defense: 500,
  },
  {
    name: "Infernal Scout",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 3,
    attack: 1000,
    defense: 600,
  },
  {
    name: "Pyroclast Wyvern",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1300,
    defense: 900,
  },
  {
    name: "Smoldering Newt",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 2,
    attack: 700,
    defense: 300,
  },
  {
    name: "Ashen Dragonet",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 2,
    attack: 800,
    defense: 800,
  },
  {
    name: "Kindled Basilisk",
    rarity: "common",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1500,
    defense: 1100,
  },
  {
    name: "Infernal Vanguard",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1600,
    defense: 1000,
  },
  {
    name: "Blazetail Guardian",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1400,
    defense: 1400,
  },
  {
    name: "Crimson Firebreather",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1800,
    defense: 800,
  },
  {
    name: "Volcanic Striker",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1700,
    defense: 900,
  },
  {
    name: "Flame Herald",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 3,
    attack: 1200,
    defense: 1000,
  },
  {
    name: "Magma Carrier",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 5,
    attack: 2000,
    defense: 1400,
  },
  {
    name: "Pyre Sentinel",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1500,
    defense: 1500,
  },
  {
    name: "Infernal Charger",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 4,
    attack: 1900,
    defense: 600,
  },
  {
    name: "Infernal Warlord",
    rarity: "rare",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 6,
    attack: 2400,
    defense: 1800,
  },
  {
    name: "Volcanic Dragon",
    rarity: "rare",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 7,
    attack: 2600,
    defense: 2000,
  },
  {
    name: "Infernal Ravager",
    rarity: "rare",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 5,
    attack: 2200,
    defense: 1600,
  },
  {
    name: "Pyromancer Drake",
    rarity: "rare",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 5,
    attack: 2000,
    defense: 1200,
  },
  {
    name: "Hellfire Wyrm",
    rarity: "rare",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 6,
    attack: 2300,
    defense: 1400,
  },
  {
    name: "Infernal Tyrant",
    rarity: "epic",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 7,
    attack: 2800,
    defense: 2200,
  },
  {
    name: "Volcanic Behemoth",
    rarity: "epic",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 8,
    attack: 3000,
    defense: 2400,
  },
  {
    name: "Infernal Phoenix",
    rarity: "epic",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 7,
    attack: 2500,
    defense: 2000,
  },
  {
    name: "Infernal Overlord Vyraxis",
    rarity: "legendary",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 9,
    attack: 3200,
    defense: 2500,
  },
  {
    name: "Apocalypse Dragon",
    rarity: "legendary",
    cardType: "creature",
    archetype: "infernal_dragons",
    cost: 10,
    attack: 3500,
    defense: 3000,
  },

  // Spells (10)
  {
    name: "Dragon's Fury",
    rarity: "common",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 3,
  },
  {
    name: "Volcanic Eruption",
    rarity: "common",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 3,
  },
  {
    name: "Infernal Recovery",
    rarity: "common",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 2,
  },
  {
    name: "Fire Breathing",
    rarity: "common",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 2,
  },
  {
    name: "Sudden Ignition",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 3,
  },
  {
    name: "Infernal Barrier",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 3,
  },
  {
    name: "Scorching Wind",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 3,
  },
  {
    name: "Infernal Furnace",
    rarity: "rare",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 4,
  },
  {
    name: "Dragon's Hoard",
    rarity: "rare",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 4,
  },
  {
    name: "Volcanic Lair",
    rarity: "rare",
    cardType: "spell",
    archetype: "infernal_dragons",
    cost: 4,
  },

  // Traps (5)
  {
    name: "Flame Trap",
    rarity: "common",
    cardType: "trap",
    archetype: "infernal_dragons",
    cost: 2,
  },
  {
    name: "Burning Revenge",
    rarity: "common",
    cardType: "trap",
    archetype: "infernal_dragons",
    cost: 2,
  },
  {
    name: "Ring of Fire",
    rarity: "uncommon",
    cardType: "trap",
    archetype: "infernal_dragons",
    cost: 3,
  },
  {
    name: "Infernal Presence",
    rarity: "uncommon",
    cardType: "trap",
    archetype: "infernal_dragons",
    cost: 3,
  },
  {
    name: "Dragon's Wrath",
    rarity: "epic",
    cardType: "trap",
    archetype: "infernal_dragons",
    cost: 5,
  },
] as const;

export const ABYSSAL_DEPTHS_CARDS: readonly CardSeed[] = [
  // Monsters (30)
  {
    name: "Reef Crab",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 2,
    attack: 600,
    defense: 800,
  },
  {
    name: "Coral Serpent",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 3,
    attack: 1000,
    defense: 600,
  },
  {
    name: "Tidal Eel",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 2,
    attack: 800,
    defense: 400,
  },
  {
    name: "Murky Triton",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 3,
    attack: 1200,
    defense: 1000,
  },
  {
    name: "Deep Mermaid",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 4,
    attack: 1400,
    defense: 800,
  },
  {
    name: "Glacial Crab",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 2,
    attack: 500,
    defense: 1200,
  },
  {
    name: "Undertow Shark",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 4,
    attack: 1300,
    defense: 700,
  },
  {
    name: "Frozen Hydra",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 3,
    attack: 1100,
    defense: 900,
  },
  {
    name: "Sunken Squid",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 2,
    attack: 900,
    defense: 500,
  },
  {
    name: "Riptide Whale",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 4,
    attack: 1500,
    defense: 1300,
  },
  {
    name: "Abyssal Siren",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 2,
    attack: 700,
    defense: 600,
  },
  {
    name: "Oceanic Jellyfish",
    rarity: "common",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 1,
    attack: 400,
    defense: 400,
  },
  {
    name: "Tidal Serpent",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 4,
    attack: 1600,
    defense: 1200,
  },
  {
    name: "Glacial Hydra",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 5,
    attack: 1400,
    defense: 1600,
  },
  {
    name: "Reef Guardian",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 4,
    attack: 1200,
    defense: 1800,
  },
  {
    name: "Deep Hunter",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 4,
    attack: 1800,
    defense: 800,
  },
  {
    name: "Frozen Leviathan",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 5,
    attack: 1700,
    defense: 1400,
  },
  {
    name: "Murky Stalker",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 4,
    attack: 1500,
    defense: 1000,
  },
  {
    name: "Coral Enchantress",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 3,
    attack: 1300,
    defense: 1100,
  },
  {
    name: "Undertow Kraken",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 5,
    attack: 2000,
    defense: 1600,
  },
  {
    name: "Abyssal Lord",
    rarity: "rare",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 6,
    attack: 2200,
    defense: 1800,
  },
  {
    name: "Tidal Dragon",
    rarity: "rare",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 7,
    attack: 2400,
    defense: 2000,
  },
  {
    name: "Glacial Monarch",
    rarity: "rare",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 6,
    attack: 2000,
    defense: 2400,
  },
  {
    name: "Deep Sea Terror",
    rarity: "rare",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 7,
    attack: 2600,
    defense: 1600,
  },
  {
    name: "Frozen Sovereign",
    rarity: "rare",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 6,
    attack: 2100,
    defense: 2100,
  },
  {
    name: "Leviathan Prime",
    rarity: "epic",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 8,
    attack: 2800,
    defense: 2400,
  },
  {
    name: "Abyssal Tyrant",
    rarity: "epic",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 8,
    attack: 2600,
    defense: 2800,
  },
  {
    name: "Kraken Overlord",
    rarity: "epic",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 8,
    attack: 3000,
    defense: 2200,
  },
  {
    name: "Tidal Emperor Nereus",
    rarity: "legendary",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 9,
    attack: 3200,
    defense: 2800,
  },
  {
    name: "Leviathan of the Abyss",
    rarity: "legendary",
    cardType: "creature",
    archetype: "abyssal_horrors",
    cost: 10,
    attack: 3800,
    defense: 4000,
  },

  // Spells (10)
  {
    name: "Tidal Wave",
    rarity: "common",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 3,
  },
  {
    name: "Glacial Blessing",
    rarity: "common",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 2,
  },
  {
    name: "Deep Recovery",
    rarity: "common",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 2,
  },
  {
    name: "Frozen Touch",
    rarity: "common",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 2,
  },
  {
    name: "Sudden Freeze",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 3,
  },
  {
    name: "Abyssal Shield",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 3,
  },
  {
    name: "Riptide Counter",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 3,
  },
  {
    name: "Endless Depths",
    rarity: "rare",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 4,
  },
  {
    name: "Frozen Prison",
    rarity: "rare",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 4,
  },
  {
    name: "Abyssal Trench",
    rarity: "rare",
    cardType: "spell",
    archetype: "abyssal_horrors",
    cost: 4,
  },

  // Traps (5)
  {
    name: "Frozen Ambush",
    rarity: "common",
    cardType: "trap",
    archetype: "abyssal_horrors",
    cost: 2,
  },
  {
    name: "Tidal Revenge",
    rarity: "common",
    cardType: "trap",
    archetype: "abyssal_horrors",
    cost: 2,
  },
  {
    name: "Icy Presence",
    rarity: "uncommon",
    cardType: "trap",
    archetype: "abyssal_horrors",
    cost: 3,
  },
  {
    name: "Abyssal Barrier",
    rarity: "uncommon",
    cardType: "trap",
    archetype: "abyssal_horrors",
    cost: 3,
  },
  {
    name: "Depth Rejection",
    rarity: "epic",
    cardType: "trap",
    archetype: "abyssal_horrors",
    cost: 5,
  },
] as const;

export const IRON_LEGION_CARDS: readonly CardSeed[] = [
  // Monsters (30)
  {
    name: "Iron Soldier",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 3,
    attack: 1000,
    defense: 1200,
  },
  {
    name: "Bronze Centurion",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 3,
    attack: 1200,
    defense: 1000,
  },
  {
    name: "Steel Knight",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 4,
    attack: 1400,
    defense: 1400,
  },
  {
    name: "Armored Recruit",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 2,
    attack: 600,
    defense: 800,
  },
  {
    name: "Battle Sentinel",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 4,
    attack: 1100,
    defense: 1500,
  },
  {
    name: "Plated Defender",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 3,
    attack: 800,
    defense: 1600,
  },
  {
    name: "Siege Tank",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 4,
    attack: 1500,
    defense: 1100,
  },
  {
    name: "Fortified Warden",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 3,
    attack: 700,
    defense: 1400,
  },
  {
    name: "Heavy Golem",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 4,
    attack: 1300,
    defense: 1300,
  },
  {
    name: "Chrome Mech",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 2,
    attack: 900,
    defense: 900,
  },
  {
    name: "Titanium Guard",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 3,
    attack: 500,
    defense: 1800,
  },
  {
    name: "Battle Juggernaut",
    rarity: "common",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 4,
    attack: 1600,
    defense: 1200,
  },
  {
    name: "Iron Commander",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 5,
    attack: 1700,
    defense: 1500,
  },
  {
    name: "Steel Colossus",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 5,
    attack: 1400,
    defense: 2000,
  },
  {
    name: "Siege Master",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 5,
    attack: 1900,
    defense: 1300,
  },
  {
    name: "Armored Vanguard",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 4,
    attack: 1600,
    defense: 1600,
  },
  {
    name: "Fortified General",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 5,
    attack: 1800,
    defense: 1800,
  },
  {
    name: "Heavy Sentinel",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 5,
    attack: 1200,
    defense: 2200,
  },
  {
    name: "Chrome Centurion",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 4,
    attack: 1500,
    defense: 1700,
  },
  {
    name: "Plated Champion",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 5,
    attack: 2000,
    defense: 1400,
  },
  {
    name: "Iron Warlord",
    rarity: "rare",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 6,
    attack: 2400,
    defense: 2000,
  },
  {
    name: "Titanium Dragon",
    rarity: "rare",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 7,
    attack: 2200,
    defense: 2600,
  },
  {
    name: "Siege Behemoth",
    rarity: "rare",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 7,
    attack: 2600,
    defense: 1800,
  },
  {
    name: "Fortress Guardian",
    rarity: "rare",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 6,
    attack: 1800,
    defense: 3000,
  },
  {
    name: "Steel Overlord",
    rarity: "rare",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 6,
    attack: 2300,
    defense: 2300,
  },
  {
    name: "Iron Titan",
    rarity: "epic",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 8,
    attack: 2800,
    defense: 3000,
  },
  {
    name: "Adamantine Colossus",
    rarity: "epic",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 8,
    attack: 2400,
    defense: 3200,
  },
  {
    name: "Fortress Prime",
    rarity: "epic",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 7,
    attack: 2600,
    defense: 2800,
  },
  {
    name: "Iron Marshal Ferrum",
    rarity: "legendary",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 9,
    attack: 3000,
    defense: 3200,
  },
  {
    name: "Iron Emperor Maximus",
    rarity: "legendary",
    cardType: "creature",
    archetype: "nature_spirits",
    cost: 10,
    attack: 3500,
    defense: 4500,
  },

  // Spells (10)
  {
    name: "Legion's Strength",
    rarity: "common",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 3,
  },
  {
    name: "Armored Aura",
    rarity: "common",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 2,
  },
  {
    name: "Iron Recovery",
    rarity: "common",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 2,
  },
  {
    name: "Defensive Formation",
    rarity: "common",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 2,
  },
  {
    name: "Quick Reinforcement",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 3,
  },
  {
    name: "Iron Wall",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 3,
  },
  {
    name: "Counter Assault",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 3,
  },
  {
    name: "Eternal Fortification",
    rarity: "rare",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 4,
  },
  {
    name: "Legion's Arsenal",
    rarity: "rare",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 4,
  },
  {
    name: "Iron Fortress",
    rarity: "rare",
    cardType: "spell",
    archetype: "nature_spirits",
    cost: 4,
  },

  // Traps (5)
  {
    name: "Armored Surprise",
    rarity: "common",
    cardType: "trap",
    archetype: "nature_spirits",
    cost: 2,
  },
  {
    name: "Legion's Stand",
    rarity: "common",
    cardType: "trap",
    archetype: "nature_spirits",
    cost: 2,
  },
  {
    name: "Fortified Field",
    rarity: "uncommon",
    cardType: "trap",
    archetype: "nature_spirits",
    cost: 3,
  },
  {
    name: "Iron Discipline",
    rarity: "uncommon",
    cardType: "trap",
    archetype: "nature_spirits",
    cost: 3,
  },
  {
    name: "Impenetrable Wall",
    rarity: "epic",
    cardType: "trap",
    archetype: "nature_spirits",
    cost: 5,
  },
] as const;

export const STORM_RIDERS_CARDS: readonly CardSeed[] = [
  // Monsters (30)
  {
    name: "Zephyr Falcon",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 3,
    attack: 1000,
    defense: 600,
  },
  {
    name: "Wind Sprite",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 1,
    attack: 600,
    defense: 400,
  },
  {
    name: "Gale Harpy",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 3,
    attack: 1200,
    defense: 800,
  },
  {
    name: "Swift Eagle",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 4,
    attack: 1400,
    defense: 600,
  },
  {
    name: "Thunder Hawk",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 3,
    attack: 1100,
    defense: 900,
  },
  {
    name: "Storm Condor",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 2,
    attack: 800,
    defense: 600,
  },
  {
    name: "Lightning Rider",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 4,
    attack: 1300,
    defense: 700,
  },
  {
    name: "Cyclone Harpy",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 3,
    attack: 1000,
    defense: 800,
  },
  {
    name: "Tempest Sparrow",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 1,
    attack: 500,
    defense: 300,
  },
  {
    name: "Wind Roc",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 4,
    attack: 1500,
    defense: 1000,
  },
  {
    name: "Zephyr Rider",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 2,
    attack: 900,
    defense: 500,
  },
  {
    name: "Gale Condor",
    rarity: "common",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 3,
    attack: 1100,
    defense: 700,
  },
  {
    name: "Storm Vanguard",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 4,
    attack: 1600,
    defense: 1000,
  },
  {
    name: "Tornado Eagle",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 4,
    attack: 1700,
    defense: 900,
  },
  {
    name: "Lightning Phoenix",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 4,
    attack: 1500,
    defense: 1200,
  },
  {
    name: "Hurricane Griffin",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 5,
    attack: 1800,
    defense: 800,
  },
  {
    name: "Cyclone Lord",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 4,
    attack: 1400,
    defense: 1400,
  },
  {
    name: "Thunder Champion",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 5,
    attack: 2000,
    defense: 1000,
  },
  {
    name: "Zephyr Herald",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 3,
    attack: 1200,
    defense: 1000,
  },
  {
    name: "Gale Striker",
    rarity: "uncommon",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 4,
    attack: 1900,
    defense: 600,
  },
  {
    name: "Storm Warlord",
    rarity: "rare",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 6,
    attack: 2200,
    defense: 1600,
  },
  {
    name: "Tornado Thunderbird",
    rarity: "rare",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 6,
    attack: 2400,
    defense: 1400,
  },
  {
    name: "Hurricane Dragon",
    rarity: "rare",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 7,
    attack: 2600,
    defense: 1800,
  },
  {
    name: "Lightning Sovereign",
    rarity: "rare",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 6,
    attack: 2100,
    defense: 1900,
  },
  {
    name: "Tempest Commander",
    rarity: "rare",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 6,
    attack: 2300,
    defense: 1500,
  },
  {
    name: "Storm Tyrant",
    rarity: "epic",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 7,
    attack: 2800,
    defense: 2000,
  },
  {
    name: "Tornado Overlord",
    rarity: "epic",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 7,
    attack: 2600,
    defense: 2200,
  },
  {
    name: "Lightning Emperor",
    rarity: "epic",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 8,
    attack: 3000,
    defense: 1800,
  },
  {
    name: "Storm Archon Zelos",
    rarity: "legendary",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 9,
    attack: 3200,
    defense: 2400,
  },
  {
    name: "Tempest Archon",
    rarity: "legendary",
    cardType: "creature",
    archetype: "storm_elementals",
    cost: 8,
    attack: 3200,
    defense: 2800,
  },

  // Spells (10)
  {
    name: "Gale Blast",
    rarity: "common",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 3,
  },
  {
    name: "Swift Strike",
    rarity: "common",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 2,
  },
  {
    name: "Wind Recovery",
    rarity: "common",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 2,
  },
  { name: "Tailwind", rarity: "common", cardType: "spell", archetype: "storm_elementals", cost: 2 },
  {
    name: "Sudden Gust",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 3,
  },
  {
    name: "Evasive Maneuver",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 3,
  },
  {
    name: "Lightning Dash",
    rarity: "uncommon",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 3,
  },
  {
    name: "Endless Storm",
    rarity: "rare",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 4,
  },
  {
    name: "Rider's Momentum",
    rarity: "rare",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 4,
  },
  {
    name: "Storm's Eye",
    rarity: "rare",
    cardType: "spell",
    archetype: "storm_elementals",
    cost: 4,
  },

  // Traps (5)
  { name: "Wind Trap", rarity: "common", cardType: "trap", archetype: "storm_elementals", cost: 2 },
  {
    name: "Thunder Revenge",
    rarity: "common",
    cardType: "trap",
    archetype: "storm_elementals",
    cost: 2,
  },
  {
    name: "Cyclone Zone",
    rarity: "uncommon",
    cardType: "trap",
    archetype: "storm_elementals",
    cost: 3,
  },
  {
    name: "Storm Barrier",
    rarity: "uncommon",
    cardType: "trap",
    archetype: "storm_elementals",
    cost: 3,
  },
  {
    name: "Tempest Counter",
    rarity: "epic",
    cardType: "trap",
    archetype: "storm_elementals",
    cost: 5,
  },
] as const;
